# Generated by Django 3.0.6 on 2020-05-27 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('profile', models.TextField()),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('extracurricular', models.TextField()),
                ('skills', models.TextField()),
                ('edited_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
